name: Build and publish a Docker image for master branch
on:
    push:
        branches:
            - master
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: 'arm64,arm'

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
              with:
                  platforms: linux/arm64,linux/amd64,linux/arm/v7

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: ${{ steps.buildx.outputs.platforms }}
                  push: true
                  tags: |
                      ${{ github.repository }}:latest
                      ghcr.io/${{ github.repository }}:latest
